# Generated by Django 3.0.7 on 2020-07-13 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together={('category', 'brand', 'slug')},
        ),
    ]
